version = 1
SPDX-PackageName = "QDA Tag Tree, tagtree.qdaaddon.de.fordes.qdatreehelper, and libreoffice-qda-tagtree"
SPDX-PackageSupplier = "Mirian Margiani <mixosaurus+ichthyo@pm.me>"
SPDX-PackageDownloadLocation = "https://codeberg.org/ichthyosaurus/libreoffice-qda-tagtree"

[[annotations]]
path = "example-**.odt"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2022 Mirian Margiani"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileComment = "These documents mostly contain text from Henry David Thoreau's\n    1854 book \"Walden\", which is in the public domain.\n    Each document's metadata contains license info as well."

[[annotations]]
path = "qda-tagtree/description/**.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 Jan Dittrich"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "qda-tagtree/image/icon.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 Jan Dittrich"
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileComment = "Original sources are not available."

[[annotations]]
path = "qda-tagtree/registration/license.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2017 Jan Dittrich", "2022 Mirian Margiani"]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileComment = "GPL license header for the whole project. Required by LibreOffice."

[[annotations]]
path = "qda-tagtree/src/pythonpath/ui/qdaTreePanel_UI.py"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 Jan Dittrich"
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileComment = "Generated by unodit (https://github.com/kelsa-pi/unodit)."

[[annotations]]
path = "qda-tagtree/templates/tag_report.odt"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Mirian Margiani"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "dist/screenshot-**.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Mirian Margiani"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"
